---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
#Reproducible Research Peer-Graded Project

## Loading and preprocessing the data

```{r}

a_data <- read.csv('activity.csv', header = TRUE, sep=",",
                  colClasses=c("numeric", "character", "numeric"))


a_data$date <- as.Date(a_data$date, format = "%Y-%m-%d")
a_data$interval <- as.factor(a_data$interval)
```



## What is mean total number of steps taken per day?

```{r}
steps_taken_per_day <- aggregate(steps ~ date, a_data, sum)
colnames(steps_taken_per_day) <- c("date","steps")
```

```{r}
hist_O<-ggplot(steps_taken_per_day, aes(x = steps)) + 
  geom_histogram(binwidth = 1000) + 
  labs(title="Histogram of Steps Taken per Day", 
       x = "Number of Steps per Day", y = "Number of times in a day(Count)") + theme_bw()
print(hist_O)
```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
